name: Container Tests
on:
  pull_request:
  push: { branches: master }

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    env:
      COMPOSE_FILE: docker-compose.yml

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Start services
      run: docker-compose up -d
      
    - name: Healthcheck
      run: docker-compose run playsms-server playsmsd status
      
    - name: Stop services
      run: docker-compose stop
