name: Container Tests
on:
  pull_request:
  push: { branches: master }

jobs:
  test:
    name: Run test suite
    runs-on: ubuntu-latest
    env:
      COMPOSE_FILE: docker-compose.yml

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run tests
      run: docker-compose up
